/*Generated by CpsDbHelper CodeGenerator, require CpsDbHelper version >= 
Source code at https://github.com/Jishun/cpsdbhelper
*/
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace CpsDbHelper
{
    
    public partial class Table2
    {
        
        
        public int Id { get; set; }
        
        
        public string Name { get; set; }
        
        
        public int? ForId { get; set; }
        
        
        public long? ForName { get; set; }
        
        
        public int? Descript { get; set; }
        
        
    }
}