/*Generated by CpsDbHelper CodeGenerator, require CpsDbHelper version >= 
Source code at https://github.com/djsxp/cpsdbhelper
*/
using System;

namespace CpsDbHelper
{
    public partial class Table2
    {
        
        public int Id { get; set; }
        
        public string Name { get; set; }
        
        public int? Descript { get; set; }
        
    }
}